### PR TITLE
Add postamble to every page

### PR DESCRIPTION
**Pull request by winny-**
I am not sure if this was intentional- postamble is only applied to individual bog post pages, whereas preamble is applied to every page.

In the interests of backwards compatibility, maybe one should add a customize option to choose when to add the postamble to a page?

### CODE REVIEW

**Comment by MunGell** [comment]
Should we also consider moving 

```elisp
"<div id=\"archive\">\n"
"<a href=\"" org-static-blog-archive-file "\">" (org-static-blog-gettext 'other-posts) "</a>\n"
"</div>\n"
```

from `org-static-blog-assemble-multipost-page` to be the default value for `org-static-blog-page-postamble` to be consistent with footer/postamble contents on every page?

**Comment by bastibe** [comment]
Sorry for the late response, I was on vacation.

The postamble is used for comments etc., which should only show up on each post's page, but not on the front page and the archive and such. I agree however, that this is a bad name for the variable. Ideally, it should be possible to have a different postamble for posts and other pages.

Would you like to take a stab at that?

**Comment by bastibe** [comment]
@MunGell why would we do that?

**Comment by MunGell** [comment]
@bastibe I've actually developed the idea a little bit further...

We basically need to have 2 sets of pre/postambles: 
* For pages in general (logo headings, footer copyright notices, etc.), which is applicable to all pages, including posts and auto-generated pages like Archive and Tags.
* For posts (publication dates, comments, any other meta-info, etc.).

I've implemented it in my version of the script.
If there is interest - I can create a PR here for review.

**Comment by bastibe** [comment]
I'd be very interested in your changes! However, we should try to not break existing user customizations, so the existing variables need to stay in place, and can't change behavior unless absolutely necessary.

**Comment by winny-** [comment]
Hi @MunGell this seems like a more comprehensive solution than what is offered in this PR. Are you still interested in opening a PR for it?

**Comment by MunGell** [comment]
Hi @winny- 

I am afraid I might not be able to create a PR for this change in near future.
If you are willing to update this PR with separation of page/post pre/postables – please go ahead :) Otherwise, I will try to create a PR in the next couple of weeks.

Thanks for your feedback!

**Comment by MassimoLauria** [comment]
I believe #54 makes this issue obsolete.

**Pull request closed without merging**
