### PR TITLE
Add option to use HTML5 semantic elements

### PR DESCRIPTION
**Pull request by geeklhem**
Introduce new custom option `org-static-blog-use-semantic-html` that
default to `nil`.

If set to `t`
- replace `<div id="preamble" class="status">` with `<header>`
- replace `<div id="postamble" class="status">` with `<footer>`
- replace `<div id="content">` with `<main>`
- replace `<div class="post-date">` with `<time>`

Regardless of the value:
- wrap each post in `org-static-blog-assemble-multipost-page` in an `<article>`
- wrap the title and date of each article in an `<header>`

As discussed in bastibe/org-static-blog#8

### CODE REVIEW

**Comment by bastibe** [comment]
> Should we keep the `class="status"` too ?

No, I don't think these are necessary with the new elements. The HTML tags are easy enough to work with in CSS.

**Comment by IsakFalk** [comment]
Hello, is there a plan to integrate this?

**Comment by bastibe** [comment]
If someone is willing to push this forward, gladly.

**Comment by IsakFalk** [comment]
@bastibe I will try to fix this.

**Comment by bastibe** [comment]
@IsakFalk, thank you very much! I'll be looking forward to it!

**Comment by bastibe** [comment]
I am closing this due to inactivity. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
