### PR TITLE
Add a function to clean org-static-blog-publish-directory

### PR DESCRIPTION
**Pull request by adithyaov**

### CODE REVIEW

**Comment by bastibe** [comment]
Could you comment on when this function would be needed?

**Comment by adithyaov** [comment]
Say we want to delete a post. Deleting the .org file and publishing the blog does not automatically delete the .html file produced.
I've run into this problem when I renamed a .org file and noticed that the .html file with the previous name existed as well.

In general I think every program that produces files should have some mechanism to clean them up as well.

**Comment by bastibe** [comment]
In that case, it might be better to only delete HTML files that don't have a matching ORG file, I think. Would you like to add this functionality to the PR?

**Comment by adithyaov** [comment]
That's not the main objective of this function. It is analogous to `make clean`. The idea is to delete all build objects, in this case, all the generated files.

This can also be used to cleanly generate the site.

**Comment by bastibe** [comment]
I am a bit reluctant to merge this, because users might put custom HTML files into their `publish-directory`. Simply deleting all HTML and XML files feels very unsafe, to be honest.

**Comment by adithyaov** [comment]
> Simply deleting all HTML and XML files feels very unsafe, to be honest.

How about an option to specify `extra-files` that are treated differently?

**Comment by bastibe** [comment]
Perhaps that, and let's not touch any file outside of `org-static-blog-publish-directory`. (I think we're not publishing anything to subdirectories, right?)

**Comment by adithyaov** [comment]
> I think we're not publishing anything to subdirectories, right?

No. We have a flat directory structure.

**Comment by bastibe** [comment]
I am closing this due to inactivity. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
