### PR TITLE
General improvements

### LINKED ISSUE #76: Wrong number of arguments error when exporting with org-static-blog-enable-tags t
I'm using org-static-blog-20201117.906. I created the file

`#+title: First post
#+date: <2020-11-18 08:08>
#+filetags: test random

I am trying out ~org-static-blog~ for the first time. I want to blog a bit, and I like org so maybe this is the correct solution for me.`

and run org-static-blog-publish, which results in the error
`org-static-blog-assemble-multipost-page: Wrong number of arguments: (lambda (dir filename) "Concat filename to another path interpreted as a directory." (concat (file-name-as-directory dir) filename)), 4`

The post is correctly exported and the files archive.html, index.html, rss.xml, and tags.html are created correctly but tag-test.html and tag-random.html are not created.

All works correctly when org-static-blog-enable-tags is set to nil

### PR DESCRIPTION
**Pull request by adithyaov**
- Commit 1: Closes #76 
- Commit 2: Replace regex replace with a simpler implementation
- Commit 3: Abstract out the template (In the future, maybe we could let the user choose his own template)
- ~Commit 4:Test cases. This is a naive test case that should manually be run by the developer. Constructive criticism is highly appreciated.~
- Commit 4: Replaces concat with concat-to-dir in the code that creates a new blog post.

### CODE REVIEW

**Comment by adithyaov** [comment]
`test/config-1/` etc. are basically valid generated Html elements.
The (manual) test is basically creating a `result` given the same configuration and compare the files for that commit.

**Comment by bastibe** [comment]
Wow, that's quite a pull request! Improving the code, fixing a bug, and introducing tests. Great work!

I haven't tested the code myself, and I won't have the time to do so for a while. But if you think it's ready, I'd be happy to merge it!

**Comment by adithyaov** [comment]
Looks like some non-required code has crept through. I forgot to disable the preamble and postamble. My own config has crept in. I'll need to fix that and somehow automate the tests.

I'll also have to remove the RSS file as comparing that would be unfair because the date will not be the same.

**Comment by adithyaov** [comment]
For now, maybe I'll remove the test cases. I'll need to think more properly about that.

**Comment by adithyaov** [comment]
@bastibe This can probably be merged. I'll get back to you with a stable test-suite in the near future.

**Pull request merged**
