### PR TITLE
Add option to use HTML5 semantic elements [Non-stale]

### PR DESCRIPTION
**Pull request by IsakFalk**
This is the same as #14 as I actually just worked of the fork https://github.com/geeklhem/org-static-blog. Let me know if you want me to change the title or if it's possible to take over the other merge request.

### CODE REVIEW

**Comment by IsakFalk** [comment]
Will change to a non-master branch.

**Comment by bastibe** [comment]
This seems to be work in progress, right? Please notify me once you would like a review, and are ready to merge.

**Comment by IsakFalk** [comment]
@bastibe yes, will notify you when I make some more progress on this.

**Comment by bastibe** [comment]
I am closing this due to inactivity. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
