### PR TITLE
Configurable whitespace-removal in suggested filename

### PR DESCRIPTION
**Pull request by magthe**
Manually modifying the filename is nice, but a bit of a drag when having to do it often. I've made it configurable in my own setup and I thought I'd share it in case others think it's a good idea too.

### CODE REVIEW

**Comment by bastibe** [comment]
That looks useful, thank you for your contribution. Could you give an example of the kinds of file names you use it for?

**Comment by magthe** [comment]
It happens that I want a `/` in the title, e.g. when writing about a project on GitHub. So in my setup I now have the following to deal with it:

```
(setq org-static-blog-suggested-filename-cleaning-regexp (rx (or "/" (in white))))
```

**Comment by bastibe** [comment]
Thank you for the clarification. I think it would be useful to give this example in the documentation or the FAQ. 

Would you like to add that before we merge?

**Comment by magthe** [comment]
I made a first attempt at documenting it, with a small example. Let me know what you think.

**Comment by bastibe** [comment]
Wonderful! Thank you very much!

Let me know if you think this is ready to merge.

**Comment by magthe** [comment]
Yes, if you are happy with it then please go ahead and merge it.

**Comment by bastibe** [comment]
Thank you very much!

Do you urgently need this in a new tagged release?

**Pull request merged**
