### PR TITLE
Fix problem for previewing posts

### PR DESCRIPTION
**Pull request by dinoallo**
The original method of finding previewing paragraph will cause errors if paragraphs reside in one of the `<div>` container created by org-mode. That is, some `</div>` will be missing. Therefore the whole page can't not be randered correctly.
Instead of excerpting rendered HTML from title to the first paragraph, the new method re-renders title, date, tags from post-filename seperately, and only excerpts the first paragraph to ensure correct rendring.

### CODE REVIEW

**Comment by bastibe** [comment]
This looks good as far as I can see.

Does this recreate the previous HTML exactly, apart from the problem with `<div>` you mentioned?

**Comment by dinoallo** [comment]
> This looks good as far as I can see.
> 
> Does this recreate the previous HTML exactly, apart from the problem with `<div>` you mentioned?

This recreates title, date, tags exactly like the published HTML (except `h1` tag for title changes to `h2` for previewing), and only excerpts the first paragraph(which is enclosed by the first `<p></p>` ). It's hard to tell if the previous HTML is perfectly enclosed.
So no, it does not include the HTML prior to the first paragraph :( to avoid causing additional rendering problems.

**Comment by bastibe** [comment]
I am not a user of this feature. Do you think this will break existing installations?

**Comment by dinoallo** [comment]
> I am not a user of this feature. Do you think this will break existing installations?

I think for all installations the previewing HTML will be rendered fine without any errors (like missing tags) since the new method ensure only including properly enclosed tags compared to the old one.

**Comment by bastibe** [comment]
Cool, thank you very much!

**Comment by jaor** [comment]
FWIW, this has broken previews for me in several ways.  One is that there are posts that don't start with a paragraph, but with a list or an image.  For the former, now we get an error; for the latter, the image is gone from the preview, where it used to be.  Another is spacing: for some reason, the post title and the date get a wide margin in between, and the tags marker and the next title are next to each other (you can see the ugly effect in my blog entry page, https://jao.io).

I am afraid i don't have much time right now to go over the HTML and see what's different, so i'll probably just re-define org-static-blog-get-preview to its preview incarnation for the time being, but just wanted to let you know :)

**Comment by dinoallo** [comment]
> FWIW, this has broken previews for me in several ways.  One is that there are posts that don't start with a paragraph, but with a list or an image.  For the former, now we get an error; for the latter, the image is gone from the preview, where it used to be.  Another is spacing: for some reason, the post title and the date get a wide margin in between, and the tags marker and the next title are next to each other (you can see the ugly effect in my blog entry page, https://jao.io).
> 
> I am afraid i don't have much time right now to go over the HTML and see what's different, so i'll probably just re-define org-static-blog-get-preview to its preview incarnation for the time being, but just wanted to let you know :)

Thanks for letting me know :) I admit the fix is not perfect and it indeed may not render some of the HTML used to be rendered before (Like what you mentioned, the image, the list, etc...). And it's a cost of safe render with the current method. I will see what I can do to improve the previewing features. Sorry for the inconvenience. :(

**Comment by jaor** [comment]
On Sat, Jun 27 2020, Allo wrote:

> Thanks for letting me know :) I admit the fix is not perfect and it
> indeed may not render some of the HTML used to be rendered before
> (Like what you mentioned, the image, the list, etc...). And it's a
> cost of safe render with the current method. I will see what I can do
> to improve the previewing features. Sorry for the inconvenience. :(

no problem.  it's also possible that the problem is not entirely with
your patch, and that it might had uncovered something wrong with my css
or configuration... unfortunately, i don't have time right now to look
closer and see if that's the case; sorry about that.

**Comment by bastibe** [comment]
Should we roll back the change?

Or could you comment on what would need to be changed to make this work for you?

**Comment by jaor** [comment]
hi, sorry for the long delay answering this! i finally took a look,
and here's what this PR broke for me (after fixing the things that it
didn't break and were actually on my side, due to the CSS):

   - it decides to put the date of the post /after/ the title, which
     is inconsistent with other pages showing lists of posts, or
     individual posts, where the date comes first.  that's
     inconsistent: it'd be nice to at least have a customization
     option for it.

   - in my case, sometimes a post doesn't start with a `<p>`, but with
     an image.  with this patch, that image is ignored in the index,
     and before it it wasn't... my expectation was that the preview
     would show the image if it's the first thing in the post (it now
     shows the first paragraph after it).


i see how these things (and other) might be tricky to control or
subject to taste, but at least the date ordering shouldn't be too
hard.  and additional idea would be to allow defining and "end of
preview" maker as a user definable variable.  i could then write,
say,

          (setq org-static-blog-end-of-preview "")

and the put in my posts the `<!-- body -->` comment wherever i want
the preamble to finish... that way some posts can have a single
paragraph as preview, others 2, others an image and a paragraph, and
so on.  it doesn't look too hard to implement, but i'm low on
bandwidth right now.

**Comment by jaor** [comment]
i was thinking a bit on this, and we could have

   (defvar org-static-blog-begin-of-preview "<p>")
   (defvar org-static-blog-end-of-preview "</p>")

by default, and make the current code look for those variables instead
of literally "<p>", and everything would work as it does now while
providing the flexibility of having user-defined markers in some posts
(for that, i'd make it so that if the configured marker is not found,
we fallback to the first paragraph).

**Comment by bastibe** [comment]
I like the idea of putting an (optional) explicit marker into the code to end the preview. I am less sure about the need for a beginning marker as well, but if it's useful to someone, I won't argue the point. Does anyone want to implement it?

**Comment by jaor** [comment]
On Sun, Mar 21 2021, Bastian Bechtold wrote:

> I like the idea of putting an (optional) explicit marker into the code
> to end the preview. I am less sure about the need for a beginning
> marker as well, but if it's useful to someone, I won't argue the
> point. Does anyone want to implement it?

imagine the inverse of my image+text post, in which one wants
(sometimes) the first paragraph of the text be the preview... without a
begin marker that's not covered.  admittedly, it's a bit of a corner
case, but it's so easy to implement in addition to the end marker that i
think it's worth the trouble.

a slight nuisance is that, since the marker has to appear in the HTML,
if one wants to use an HTML comment for it one needs to write, in the
org file, something like

```org
#+begin_export html
<!-- end-of-preview -->
#+end_export
```

but well, that's `<h TAB` with org templates, so it's not /that/ bad :)

**Comment by jaor** [comment]
i finally went ahead and implemented the markers... PR submitted!

**Pull request merged**
