### PR TITLE
Plist

### PR DESCRIPTION
**Pull request by otech-nl**
Hello Bastian,

As I am tinkering with elisp at the moment, I used your project to find out what would happen if I used a plist to store post data, instead of searching a temporary buffer every time an attribute is needed.

What happened is that the code got smaller (from 24kb to 20kb) and faster (from 37s to 27s for my site), while it should be backwards compatible on the interactive functions.

I am afraid that I got carried away (e.g. I also introduced an `is_post` flag and an `org-static-blog-html-start` method) and it became a major change to your code. So I can imagine that you won't merge this PR. But I wanted to offer it anyway.

If you have time, I would appreciate your opinion.

Regards

### CODE REVIEW

**Comment by bastibe** [comment]
This looks cool, but I can't process the diff, since you re-ordered some functions (I think). Would you mind putting the functions in their original order again, so the diff becomes readable?

Also, it might be easier to cache values in the get-date/get-title/get-url/get-body functions, as opposed to a global plist. What do you think?

Lastly, I noticed that your plist always contains the exported HTML, and the HTML is exported for every entry in the plist. Currently, org-static-blog does *not* export every file every time--it instead reads the already-exported HTML from the already-exported files. On my machine, this makes `org-static-blog-publish` take 2.6 seconds.

**Comment by bastibe** [comment]
Wow, I tried to read through your changes. This is a massive amount of change.

- I like how the plist makes accessing many post attributes easier. This is really cool!
- I very much like how you factored out many functional parts into their own functions, like building the tag tree etc.

However, I am not so sure about distributing the HTML template text into several small functions. I see how that makes the control flow somewhat easier, but it also makes the HTML code much harder to understand. If anything, I would like to factor out the template texts into their own variables, with placeholder names for where the data should be inserted.

Reverting this change should also make the diff much more manageable.

**Comment by otech-nl** [comment]
Hello Bastian,

Thanks again for your feedback. It helps me to improve.

I have collected recurring HTML-fragments in 
- `osb-html-start`
- `osb-html-end`
- `osb-html-post-date`
- `osb-html-post-title`
- `osb-html-post-taglist`

Are these the functions you would like to be reverted?

Any suggestions about a solution with templates? Would skeletons be suitable?

**Comment by bastibe** [comment]
I am closing this due to inactivity. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
