### PR TITLE
Generate meta descriptions for posts for better SEO.

### PR DESCRIPTION
**Pull request by whatacold**
https://en.wikipedia.org/wiki/Meta_element#The_description_attribute has some info about meta description of HTML.

### CODE REVIEW

**Comment by bastibe** [comment]
Thank you for the pull request! I like it!

Do you think we should add the `#+description` to the new-post template in `org-static-blog-create-new-post` as well? You might need to add a sanity check in `org-static-blog-get-description` that returns `nil` if the description is empty or contains only whitespace.

**Comment by whatacold** [comment]
Hmm, haven't noticed to `org-static-blog-create-new-post`.

Since `#+filetags` is also generated anyway, I think we can add an empty`#+description` there initially, but I'm not sure whether folks will be confused by it if they aren't familiar with it, it will add some mind burden to them.

**Comment by whatacold** [comment]
Hi Bastian,

I just polish it a bit, tell me what you think:)

**Comment by bastibe** [comment]
Brilliant, this looks good!

Tell me when you're ready, and I'll happily merge it. Thank you very much for your contribution!

**Comment by whatacold** [comment]
I think that's all, also thank you for this simple and intuitive package, I'm glad I can help:)

**Pull request merged**
