### PR TITLE
localization support

### PR DESCRIPTION
**Pull request by rsm-lisper**
There are some texts hardcoded, like "Other posts" etc. I'm using org-static-blog to blog in polish language, so I need a way to include polish texts. So I created this simple localization support where all texts are in `org-static-blog-l12n-texts` assoc list, and are retrieved using `org-static-blog-l12n` function. It uses language specified by `org-static-blog-langcode`. When text is not found, it returns "[<text-id>:<lang>]", ie "[other-posts:de]".

### CODE REVIEW

**Comment by bastibe** [comment]
Wow, that's really cool! I like this a lot!

I have two suggestions, however: 

- Could you add a section to the readme that briefly explains the mechanism, and asks for additional translations as pull requests?
- Why is the variable called "l12n"? Is this a commonly-used name for translation tables?

**Comment by rsm-lisper** [comment]
- Sure, will do :)
- l12n is kind of short for localization (starts with L, ends with N and there are 12 letters in total). Or I can change it to i18n / internationalization - maybe more popular.

**Comment by rsm-lisper** [comment]
OK, so I changed `org-static-blog-l12n-texts` to `org-static-blog-texts`, and function `org-static-blog-l12n` to `org-static-blog-gettext`. It should easier to use now.

Also as per your suggestion, I added short info to readme.

**Comment by bastibe** [comment]
Thank you very much! This looks great!

**Pull request merged**
