### PR TITLE
Add postamble to all pages created

### PR DESCRIPTION
**Pull request by MassimoLauria**
The postamble should be added to all then pages created, including `archive.html`, `tags.html`, `index.html`.

### CODE REVIEW

**Comment by bastibe** [comment]
Thank you for your pull request!

The reason for the postamble not being included in every page is that it typically contains the comment section, which should only go into posts, but not into multi-page pages such as the index or the archive.

Perhaps a better way to do this would be the addition of a `org-static-blog-page-footer` (although this would be somewhat asymmetrical as the `org-static-blog-page-header` is added to the `<head>`, while the `org-static-blog-page-footer` would live in `<body>`).

**Comment by MassimoLauria** [comment]
I believe that `page-preamble` and `page-postamble` should be symmetric and should be different things than `post-preamble` and `post-postable`, which by the way exist as functions. That is a bit confusing.

The way I would do it is that have:
- page preamble and postamble as two variables
- post preamble and postamble as two variables
- I would rename the functions building the post pramble and postamble

Or even better (to reduce changes) to the current codebase, implement a specific function for comment sections, since I guess it may need the `post-filename` parameter. I haven't used them yet... still rebuilding my old blog with your great tool.

**Comment by bastibe** [comment]
I very much like your last idea, to introduce a new variable just for comment sections.

And with that, we could indeed apply the postamble to every kind of page. This sounds very reasonable. However, we will need to communicate this last part very loudly and clearly, so people aren't surprised by the change in behavior. Thank goodness the change at least doesn't break anything.

Would you like to amend this pull request to try implementing these changes?

**Comment by MassimoLauria** [comment]
A few comments about the current status of the pull-request, after our discussion.

I implemented function `org-static-blog-post-comments`, and made it so that
 - `org-static-blog-get-body` and `org-static-blog-get-preview` ignore the comments block
 - `org-static-blog-post-postamble` inserts the comments block after the tag list.

I would have done differently a couple of things:
 1. Factor out a function `org-static-blog-post-taglist` from `org-static-blog-post-postamble`.
 2. Currently the `<div id="comments"> ... </div>` block is added only if `org-static-blog-post-comments` returns a non empty string. In this way this pull-request produces the same html as before. Unfortunately the `get-body` and `get-preview` now have to do  a second `search-backward` which sometimes does not give matches. I don't have measurements but I guess such search would be more efficient if the matches was guaranteed to be there, just few bites backward.

Please tell me if you want me do to stuff a bit differently.

**Comment by bastibe** [comment]
Thank you! Looks good! This way of organizing comments is indeed far better.

Feel free to factor out `org-static-blog-post-taglist`. I agree that it would make the code a bit cleaner.

As for your second suggestion, I have two thoughts:

1. I don't think there is a performance difference, as the entire file has to be read entirely either way, and the run-time is probably dominated by disk throughput, not computation.
2. For the sake of clarity, I'd be fine with inserting a `<!-- start of org-static-blog content -->` and `<!-- end of org-static-blog content -->` or something like that, though.

Before merging, I would suggest to clean up the git history of this PR, though (rebase your changes to current master and force-push to the PR branch).

**Comment by MassimoLauria** [comment]
This should do.

**Comment by MassimoLauria** [comment]
I don't have experience with comments systems like disquis (and so far I am not using any such thing). I just assumed that their interfaces are complex enough that it is worth to use a function which knows the name of the post file. Also you own code uses 

 - page preamble : variable
 - page postamble : variable
 - post preamble : function
 - post postamble: function
 - post taglist : function (even if i did introduced the function, the implementation was already there)
 
The customization of the other aspects of a blog post seems to use the post-filename argument, so it seemed natural for the comments section to use the same scheme.

I'll give you an example on where the opposite choice was not optimal: when building the index page using previews, it would be natural to have the ellipsis in the index page to be clickable in a "read more" fashion. This is not possible because the customization variable is not parametric.

**Comment by bastibe** [comment]
> I just assumed that their interfaces are complex enough that it is worth to use a function which knows the name of the post file.

A reasonable assumption, but at least in case of Disqus indeed not so. On my own blog, the comment section is currently included in the page postamble, and identifies the blog post from its URL. I believe that most off-site comments systems are now designed to be drop-in replacements of Disqus, and therefore follow this convention (but I could be wrong on this, as I haven't researched commenting systems in a long while).

In general, I designed the page pre- and postambles to be easily customizable strings, that all users are expected to modify, whereas the post pre- and postambles are mostly implementation details of org-static-blog, that most people probably do not need to touch themselves.

I would like to keep this tradition for the comments also, which can typically be inserted as a static snippet of HTML and javascript.

If you feel this is an oversimplification, a better solution would probably allow both functions and strings in the customizable variable, and insert or call them, depending on their type. This would indeed be a very worthwhile addition to org-static-blog, although probably one to be relegated to a separate pull request.

**Comment by MassimoLauria** [comment]
Made the comment HTML into a `defcustom`. Now the patch should be ready.

**Comment by bastibe** [comment]
Thank you very much for your contribution!

Having a consistent pre- and postamble indeed cleans up the design considerably, as does the explicit inclusion of tags and comments only on posts.

Thank you for the productive discussion and pull request.

**Comment by MassimoLauria** [comment]
Thank you for your tool. It was fun to spend some quarantine time fiddling with it.

**Pull request merged**
