### PR TITLE
wrapped post preview content in a div

### PR DESCRIPTION
**Pull request by llaisdy**
This just wraps each preview section in a div, for styling.

### CODE REVIEW

**Comment by bastibe** [comment]
This seems innocuous enough, but I'm afraid it will break existing CSS rules, so we can't merge it.

However, you can advise `org-static-blog-get-preview` to wrap its output with the div, which will implement this change on your end without having to fork org-static-blog.

**Comment by llaisdy** [comment]
Ah, shame, but I understand.

> you can advise org-static-blog-get-preview to wrap its output with the div ...

Interesting, thanks.  [Advising functions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) is new to me (my emacs lisp is basic) so I will definitely try that -- adding the `advice-add` to the configs.

**Comment by llaisdy** [comment]
The `advice-add` works!  Thanks -- I'll delete my branch.

**Comment by bastibe** [comment]
Advising is such a cool feature in Emacs!

**Pull request closed without merging**
